<gedcom> ::= <line>+ <EOF>

<line> ::= <level> [<opt_xref_id>] <tag> [<line_value>] <EOL>

<level> ::= <DIGIT>+

<opt_xref_id> ::= <pointer>

<tag> ::= <alphanum>+

<line_value> ::= <line_item>+

<line_item> ::= <pointer> | <escape> | <anychar>

<escape> ::= '@' '#' <escape_text> '@' <non_at>

<non_at> ::= <ALPHA> | <DIGIT> | <otherchar> | '#'

<escape_text> ::= <anychar>+

<pointer> ::= '@' <alphanum> <pointer_string> '@'

<pointer_string> ::= <pointer_char>+

<pointer_char> ::= <ALPHA> | <DIGIT> | <otherchar> | '#'

<alphanum> ::= <ALPHA> | <DIGIT>

<anychar> ::= <ALPHA> | <DIGIT> | <otherchar> | '#' | '@@'

<ALPHA> ::= 'A' | 'B' | 'C' | ... | 'Z' | 'a' | 'b' | ... | 'z' | '_'

<DIGIT> ::= '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'

<otherchar> ::= '!' | '"' | '$' | '&' | '\'' | '(' | ')' | '*' | '+' | '-' | ',' | '.' | '/'

<EOL> ::= '\r\n' | '\n' | '\r'

<EOF> ::= /* end of file */